### ISSUE TITLE
Dynamic & static linking

### ISSUE THREAD

**Issue by Koldar** [STB1019/SkullOfSummer#13]

**Comment by majik00027** [comment]
Scusate il blackout degli ultimi due giorni, ho provato a racimolare le info necessarie ma hanno vinto impreparazione e problemi logistici. Ad ogni modo grazie mille di avermi sostituito.
AG



Inviato da Tablet Samsung.


-------- Messaggio originale --------
Da: Massimo Bono <notifications@github.com>
Data: 30/07/17 13:54 (GMT+01:00)
A: STB1019/SkullOfSummer <SkullOfSummer@noreply.github.com>
Cc: majik00027 <nessuncontattoemmeesseenne@msn.com>, Assign <assign@noreply.github.com>
Oggetto: Re: [STB1019/SkullOfSummer] Dynamic & static linking (#13)


Closed #13<https://github.com/STB1019/SkullOfSummer/issues/13>.
