### ISSUE TITLE
Index Summary need it!

### ISSUE THREAD

**Issue by RedsAnDev** [STB1019/SkullOfSummer#2]
Maybe an index is useful. I suggest to use menu as index and add a number# to order all pages.
@Koldar, we will use the same order of spreadsheetfile ?

**Comment by Koldar** [comment]
@RedsAnDev we still need to determine which is the best and most understandable index.
Said that I will gladly create at least the menu skeleton. Then we can easily permutate the menu entries.
For the moment, I suggest to avoid the page number# labelling.

Do you agree?

**Comment by RedsAnDev** [comment]
Yes, menu skeleton is the good way to organize content AND manage document status.

**Comment by Koldar** [comment]
We need a meeting to discuss the order of the menu entries as well
