### ISSUE TITLE
Request check

### ISSUE THREAD

**Issue by RedsAnDev** [STB1019/SkullOfSummer#26]
At this link, https://hub.docker.com/r/redsandev/cgir2i/
I posted a quick guide to start and see a CGI on own browser.

Can you bring to me a feedback? Just reply here. Thank you

**Comment by Koldar** [comment]
Some information: you may need to use "sudo" when performing the command "docker pull": write such information in the readme;

When performing `sudo docker run -d -p 9090:80 --name=cgi cgir2i:skull2018` docker replies me:

Unable to find image 'cgir2i:skull2018' locally

> docker: Error response from daemon: pull access denied for cgir2i, repository does not exist or may require 'docker login'.
> See 'docker run --help'.

Maybe some permission failure?

**Comment by RedsAnDev** [comment]
Solve it: to work needs to say which repo pull image → redsandev/cgr2i:sjull2018.

README updated.

**Comment by Koldar** [comment]
Ok now it works, but you need to tell the people **where and how** they can change the CGI code. Can you please update the readme with this information as well?

Something like:

- to change the CGI code go to the path XXX/YYY and change the file ZZZ as you wish.
- to compile the CGI do XXX

**Comment by Koldar** [comment]
Just pinging for reminding you the instructions on how to change the CGI code in the readme available at [https://hub.docker.com/r/redsandev/cgir2i/](https://hub.docker.com/r/redsandev/cgir2i/)
