### ISSUE TITLE
Explain comma (,) operator

### ISSUE THREAD

**Issue by Koldar** [STB1019/SkullOfSummer#3]
It's great inside a function that does not return the values you want in a one line. Useful in logs; for example:

    info("my useful log %s", getBufferStringOfEdge(edge_instance, buffer));

here `getBufferStringOfEdge` returns the number of bytes consumed, but i want the buffer referenced. No problem, just use:

    info("my useful log %s", (getBufferStringOfEdge(edge_instance, buffer), buffer));

**Comment by RedsAnDev** [comment]
Maybe a couple of example can be very useful!

**Comment by Koldar** [comment]
I agreee. There are few scenarios where comma operator is useful. The one I've quoted in this issue is the one I've encountered during my code developing.
