### ISSUE TITLE
Problematiche generali nel typedef

### ISSUE THREAD

**Issue by Koldar** [STB1019/SkullOfSummer#6]
1. "Vantaggio: posso ampliare la struttura, senza modificare alcunché sia stato definito in precedenza per gli attributi preesistenti." in che senso? lo puoi fare anche senza il typedef.
2. perché hai definito la struct "anagrafe" e poi l'hai nominata in "subject"?
3. "collection tree,*pointer_tree;". Ma compila?

**Comment by RedsAnDev** [comment]
Ho apportato le modifiche. 
01) Di fatto dipende dall struct e non dal typedef. Rimosso
02) In effetti non è chiaro. Rimosso
03) Errore mio. Corretto
