### ISSUE TITLE
Dubbi circa goto

### ISSUE THREAD

**Issue by Koldar** [STB1019/SkullOfSummer#8]
In riferimento alla sezione "Thrwoing di errori", metti per favore un esempio con tanti branch di errori. E' lì che il goto va bene usarlo. Per esempio:

    int func() {
        int retVal = 0;
        conn = connectToDatabase();

        do something
        if (!condition1) {
             retVal = 5;
             goto exit;
        }
        do something 
        if (!condition2) {
             retVal = 7;
             goto exit;
        }
        do seomthing
        if (!condition) {
             retVal = 2;
             goto exit;
        }
       do something
        exit:
             closeConnection(conn);
        return retVal;
    }

**Comment by majik00027** [comment]
Ciao, entro stasera comparira anche la pagina "altre direttive al preprocessore".
Gli esempi nelle mie pagine sono template, dato che ho fede in essi. Ho lasciato un commento nella sezione goto e ho gli esempi compilabili pronti da sostituire sebbene invoco la ridondanza di documentazione dalla mia parte. Aspetto indicazioni e buon lavoro!

**Comment by Koldar** [comment]
Se hai degli esempi interessanti mettili nella repository (come vedi nella root della repository abbiamo delle cartelle, una per argomento). Crea una cartella goto e mettici gli esempi che credi siano informativi.

Infine potresti inserire nella sezione "Throwing di errori" un esempio tipo quello che ho messo nella issue? Meglio farlo perché lì si che si vede che il goto è proprio utile!

**Comment by majik00027** [comment]
Ciao, corretto goto e uppato la pagina sulle direttive, attendo double check

**Comment by Koldar** [comment]
Ok ottimo! Chiudo la issue
